### ISSUE TITLE
Check for default starship file

### ISSUE THREAD

**Issue by sjames-au** [wintermi/zsh-starship#1]
I'm new to zsh and exploring, but, have previously used starship, so figured this might be a good fit. It took me a bit to figure out why my config was not being picked up, but, I see you expect a `STARSHIP_CONFIG` variable. I dont use that and use the default `~/.config/starship.toml` 

It might help others that the default starship file location is also checked before the plugin provided configuration steps in to make it nice right out of the box.

:)

**Comment by lorens-osman-dev** [comment]
can you explain more please, i installed ubuntu and converted to zsh shell , i tried to configure starship but i didn't work , so i backed to oh my zsh , can you explain how to setup straship with zsh properly ?

**Comment by sjames-au** [comment]
> can you explain more please, i installed ubuntu and converted to zsh shell , i tried to configure starship but i didn't work , so i backed to oh my zsh , can you explain how to setup straship with zsh properly ? 

If you set a STARSHIP_CONFIG environment variable before you call this plugin it worked for me. 

Assuming you are using starship with a default config file, you the file path I reference in the original issue. 

Out and about so can't be more specific :)

**Comment by lorens-osman-dev** [comment]
in my .zshrc :
export STARSHIP_CONFIG=/home/lorens/.config/starship.toml
eval "$(starship init zsh)"

the error is : 
[ERROR] - (starship::config): Unable to read config file content: Permission denied (os error 13)

**Comment by lorens-osman-dev** [comment]
> in my .zshrc : export STARSHIP_CONFIG=/home/lorens/.config/starship.toml eval "$(starship init zsh)"
> 
> the error is : [ERROR] - (starship::config): Unable to read config file content: Permission denied (os error 13)

I found the proplem, I installed starship using snap store, The solution : delete it, install it from the orginal source .

**Comment by wintermi** [comment]
> I found the proplem, I installed starship using snap store, The solution : delete it, install it from the orginal source .

This is most likely due to a PATH issue and the snap paths are being added later in the `.zshrc` file.

**Comment by wintermi** [comment]
> I'm new to zsh and exploring, but, have previously used starship, so figured this might be a good fit. It took me a bit to 
> figure out why my config was not being picked up, but, I see you expect a `STARSHIP_CONFIG` variable. I dont use that 
> and use the default `~/.config/starship.toml`

Apologies for the delay in responding.  I have updated the plugin to now allow for overriding the default theme using the `STARSHIP_CONFIG` environment variable or if there is a default starship configuration file present.

The README has also been updated to reflect these updates.
