### ISSUE TITLE
Documents symbol replacement seemingly broken

### ISSUE THREAD

**Issue by trekie86** [wintermi/zsh-starship#2]
I have been feverishly scouring the web to find out what symbol this is supposed to be under the [directory substitution](https://github.com/wintermi/zsh-starship/blob/7265208ebb511f6206c952e84ceccb867a00de10/theme/starship.toml#L109). It appears to be https://www.fileformat.info/info/unicode/char/f718/browsertest.htm but I have not been able to find a font that includes this symbol in the typical font packs. I'm using NerdFont Hack and it addresses all of the other symbols except for this one.

**Comment by wintermi** [comment]
Thanks @trekie86 

Good spot, I have updated the directory substitutions to the following symbols:

![image](https://github.com/wintermi/zsh-starship/assets/33818/f10bae33-61af-484d-bbfe-3ee529b8ad10)

These align nicely with what I have seen used by tools such as `lsd`.  

Let me know what you think.

**Comment by trekie86** [comment]
Ship it!

**Comment by wintermi** [comment]
Done, you can now run a `zap update` to get the latest version.
